# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Segun Bolarinwa, Ph.D
description: "Hi I'm Segun, and I'm a Data and Decision Scientist and Economist. My portfolio focuses on interesting projects I've recently undertaken, with a strong emphasis on business impact. Please visit my Github & LinkedIn pages (or download my Resume) by using the links below!"
baseurl: ""
url: "https://bolarinwathompson.github.io"

#-------------------------------
# About Section
subtitle: Data and Decision Science <span style="color:#f58506"> Portfolio </span>
location: "Norwich, UK"
resume_url: "/docs/Bolarinwa_Data_Scientist_CV.pdf"
avatar_image: "/img/Linkedin-Pic.jpg"

#-------------------------------
# Contact links
linkedin: "https://www.linkedin.com/in/segun-bolarinwa"
github: "https://github.com/bolarinwathompson"

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false
